version: '3.8'

services:
  db:
    container_name: db_mysql
    build:
      context: ./db
      dockerfile: mysql.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: web-db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - web-test
  web:
    container_name: web
    depends_on:
      - db
    build:
      context: ./web
      dockerfile: next.dockerfile
    ports:
      - "3000:3000"
    networks:
      - web-test
    # environment:
    #   DATABASE_URL: mysql://root:root@localhost:3306/web-db
volumes:
  db_mysql: {}
